/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/indoor-plant-bpaOec5a2WUaiKuF0ATci1cjCK7
Title: Indoor Plant
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const indoor_plant = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={1.1}>
          <mesh geometry={indoor_plant.nodes.Circle_0.geometry} material={indoor_plant.materials.Indoor_Plant_pot} />
          <mesh geometry={indoor_plant.nodes.Circle_1.geometry} material={indoor_plant.materials.Indoor_Plant_pot_2} />
          <mesh geometry={indoor_plant.nodes.Circle_2.geometry} material={indoor_plant.materials['Material.005']} />
          <mesh geometry={indoor_plant.nodes.Circle_3.geometry} material={indoor_plant.materials.Indoor_Plant} />
          <mesh geometry={indoor_plant.nodes.Circle_4.geometry} material={indoor_plant.materials.Indoor_Plant_ground} />
          <mesh geometry={indoor_plant.nodes.Circle_5.geometry} material={indoor_plant.materials['Material.002']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
