/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mac-draco.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { macbook_nodes, macbook_materials } = useGLTF('/mac-draco.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.04, 0.41]} rotation={[0.01, 0, 0]}>
        <group position={[0, 2.96, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={macbook_nodes.Cube008.geometry} material={macbook_materials.aluminium} />
          <mesh geometry={macbook_nodes.Cube008_1.geometry} material={macbook_materials['matte.001']} />
          <mesh geometry={macbook_nodes.Cube008_2.geometry} material={macbook_materials['screen.001']} />
        </group>
      </group>
      <mesh geometry={macbook_nodes.keyboard.geometry} material={macbook_materials.keys} position={[1.79, 0, 3.45]} />
      <group position={[0, -0.1, 3.39]}>
        <mesh geometry={macbook_nodes.Cube002.geometry} material={macbook_materials.aluminium} />
        <mesh geometry={macbook_nodes.Cube002_1.geometry} material={macbook_materials.trackpad} />
      </group>
      <mesh geometry={macbook_nodes.touchbar.geometry} material={macbook_materials.touchbar} position={[0, -0.03, 1.2]} />
    </group>
  )
}

useGLTF.preload('/mac-draco.glb')
