/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 macbook.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { macbook_nodes, macbook_materials } = useGLTF('/macbook.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.52, 0]} scale={0.1}>
        <mesh geometry={macbook_nodes.Circle001.geometry} material={macbook_materials['Frame.001']} />
        <mesh geometry={macbook_nodes.Circle001_1.geometry} material={macbook_materials['Frame.001']} />
        <mesh geometry={macbook_nodes.Circle001_2.geometry} material={macbook_materials.HeadPhoneHole} />
        <mesh geometry={macbook_nodes.Circle001_3.geometry} material={macbook_materials.USB_C_INSIDE} />
        <mesh geometry={macbook_nodes.Circle001_4.geometry} material={macbook_materials['Frame.001']} />
        <mesh geometry={macbook_nodes.Circle001_5.geometry} material={macbook_materials.TouchbarBorder} />
        <mesh geometry={macbook_nodes.Circle001_6.geometry} material={macbook_materials.Keyboard} />
        <group position={[0, -0.51, 0]} scale={5.8}>
          <mesh geometry={macbook_nodes.Circle006.geometry} material={macbook_materials['Frame.001']} />
          <mesh geometry={macbook_nodes.Circle006_1.geometry} material={macbook_materials.USB_C_INSIDE} />
        </group>
        <mesh geometry={macbook_nodes.FrontCameraRing001.geometry} material={macbook_materials['CameraRIngBlack.002']} position={[-0.15, 19.57, -16.15]} scale={5.8} />
        <group position={[-11.79, -0.15, -8.3]} scale={5.8}>
          <mesh geometry={macbook_nodes.Circle.geometry} material={macbook_materials['Keyboard.001']} />
          <mesh geometry={macbook_nodes.Circle_1.geometry} material={macbook_materials.Key} />
          <mesh geometry={macbook_nodes.Circle_2.geometry} material={macbook_materials.Touchbar} />
        </group>
        <mesh geometry={macbook_nodes.KeyboardKeyHole.geometry} material={macbook_materials['Keyboard.001']} position={[-11.79, -0.15, -8.3]} scale={5.8} />
        <mesh geometry={macbook_nodes.RubberFoot.geometry} material={macbook_materials.DarkRubber} position={[-11.95, -0.75, 7.86]} scale={5.8} />
        <group position={[0.01, -0.21, -10.56]} scale={5.8}>
          <mesh geometry={macbook_nodes.Circle012.geometry} material={macbook_materials.HingeBlack} />
          <mesh geometry={macbook_nodes.Circle012_1.geometry} material={macbook_materials.HingeMetal} />
        </group>
        <group position={[-15.03, 0.03, 0.6]} scale={5.8}>
          <mesh geometry={macbook_nodes.Circle009.geometry} material={macbook_materials['Frame.001']} />
          <mesh geometry={macbook_nodes.Circle009_1.geometry} material={macbook_materials.SpeakerHole} />
        </group>
        <group position={[12.2, 0.03, 0.6]} scale={5.8}>
          <mesh geometry={macbook_nodes.Circle003.geometry} material={macbook_materials['Frame.001']} />
          <mesh geometry={macbook_nodes.Circle003_1.geometry} material={macbook_materials.SpeakerHole} />
        </group>
        <group position={[0.01, -0.47, -10.41]} rotation={[1.31, 0, 0]} scale={5.8}>
          <mesh geometry={macbook_nodes.Circle002.geometry} material={macbook_materials['Frame.001']} />
          <mesh geometry={macbook_nodes.Circle002_1.geometry} material={macbook_materials.Screen} />
          <mesh geometry={macbook_nodes.Circle002_2.geometry} material={macbook_materials.ScreenGlass} />
          <mesh geometry={macbook_nodes.Circle002_3.geometry} material={macbook_materials.Rubber} />
          <mesh geometry={macbook_nodes.Circle002_4.geometry} material={macbook_materials.DisplayGlass} />
          <mesh geometry={macbook_nodes.AppleLogo000.geometry} material={macbook_materials['AppleLogo.004']} position={[0, -0.11, -1.8]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.58} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/macbook.gltf')
