/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: Alfking49 (https://sketchfab.com/alfking49)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pac-man-ceramic-coffee-mug-paladone-0858947c9b2c49aea198bd569bc06913
Title: Pac Man Ceramic Coffee Mug - Paladone
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const cup = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]} scale={0.05}>
        <mesh geometry={cup.nodes.Object_4.geometry} material={cup.materials['Material.001']} />
        <mesh geometry={cup.nodes.Object_5.geometry} material={cup.materials.Condensation} />
        <mesh geometry={cup.nodes.Object_6.geometry} material={cup.materials.PacmanMaze} />
        <mesh geometry={cup.nodes.Object_7.geometry} material={cup.materials.Dishwasher} />
        <mesh geometry={cup.nodes.Object_8.geometry} material={cup.materials.Bottom} />
        <mesh geometry={cup.nodes.Object_10.geometry} material={cup.materials.Coffee} scale={[0.96, 1, 0.96]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
